### ISSUE TITLE
Avoid warnings in Symfony 2.8

### ISSUE THREAD

**Issue by jcchavezs** [aferrandini/Maxmind-GeoIp#12]
From Symfony 2.8, all dependencies and parameters must be surrounded by quotes:

```
services:
    maxmind.geoip:
        class: Maxmind\Bundle\GeoipBundle\Service\GeoipManager
        arguments: [@kernel]
```
into

```
services:
    maxmind.geoip:
        class: Maxmind\Bundle\GeoipBundle\Service\GeoipManager
        arguments:
            - "@kernel"
```
